port = 9955

[substrate.localnode]
name="localnode"
enabled=true
http-endpoint = "http://localhost:9933"
ws-endpoint = "ws://localhost:9944"
runtime = "WebbProtocol"
suri = "${LOCAL_SUBSTRATE_SURI}"
[[substrate.localnode.pallets]]
pallet = "VAnchorBn254"
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
